### ISSUE TITLE
Configuring Proxy for version 2.3

### ISSUE THREAD

**Issue by BaymaxGithub** [bytefish/FcmJava#32]
Hello.
Presently there is no way to configure a proxy in the DefaultHttpClient class.
It would be nice if we could configure a proxy (hostname + port) and no optional credentials (user + password).

Thank you very much

**Comment by bytefish** [comment]
The README describes how to configure a Proxy:

* https://github.com/bytefish/FcmJava#configuring-a-proxy

It supports all Proxy functionality provided by the Apache HttpClient.

Please reopen the ticket, if this doesn't solve the problem.

**Comment by BaymaxGithub** [comment]
yes,I see. thank you

**Comment by BaymaxGithub** [comment]
But ,I got new problem.It does't work:

2017-10-30 00:07:00.452 ERROR 1 --- [scheduler-10] o.s.s.s.TaskUtils$LoggingErrorHandler    : Unexpected error occurred in scheduled task.

cn.com.inhand.fcm_server.fcmjava.http.exceptions.HttpCommunicationException: Error making POST Request
        at cn.com.inhand.fcm_server.fcmjava.client.http.apache.DefaultHttpClient.post(DefaultHttpClient.java:449) ~[classes!/:unspecified]
        at cn.com.inhand.fcm_server.fcmjava.client.FcmClient.post(FcmClient.java:100) ~[classes!/:unspecified]
        at cn.com.inhand.fcm_server.fcmjava.client.FcmClient.send(FcmClient.java:66) ~[classes!/:unspecified]
        at cn.com.inhand.fcm_server.push.PushToSpecificToken.sendPushMessage(PushToSpecificToken.java:67) ~[classes!/:unspecified]
        at cn.com.inhand.fcm_server.push.PushToSpecificToken.sendDirectMessage(PushToSpecificToken.java:60) ~[classes!/:unspecified]
        at sun.reflect.GeneratedMethodAccessor96.invoke(Unknown Source) ~[na:na]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_111]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_111]
        at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:65) ~[spring-context-4.3.5.RELEASE.jar!/:4.3.5.RELEASE]
        at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54) ~[spring-context-4.3.5.RELEASE.jar!/:4.3.5.RELEASE]
        at org.springframework.scheduling.concurrent.ReschedulingRunnable.run(ReschedulingRunnable.java:81) [spring-context-4.3.5.RELEASE.jar!/:4.3.5.RELEASE]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [na:1.8.0_111]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [na:1.8.0_111]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) [na:1.8.0_111]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) [na:1.8.0_111]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_111]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_111]
        at java.lang.Thread.run(Thread.java:745) [na:1.8.0_111]
Caused by: org.apache.http.client.ClientProtocolException: null
        at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:186) ~[httpclient-4.5.2.jar!/:4.5.2]
        at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:82) ~[httpclient-4.5.2.jar!/:4.5.2]
        at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:107) ~[httpclient-4.5.2.jar!/:4.5.2]
        at cn.com.inhand.fcm_server.fcmjava.client.http.apache.DefaultHttpClient.internalPost(DefaultHttpClient.java:344) ~[classes!/:unspecified]
        at cn.com.inhand.fcm_server.fcmjava.client.http.apache.DefaultHttpClient.post(DefaultHttpClient.java:447) ~[classes!/:unspecified]
        ... 17 common frames omitted
Caused by: org.apache.http.ProtocolException: The server failed to respond with a valid HTTP response
        at org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:151) ~[httpclient-4.5.2.jar!/:4.5.2]
        at org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:57) ~[httpclient-4.5.2.jar!/:4.5.2]
        at org.apache.http.impl.io.AbstractMessageParser.parse(AbstractMessageParser.java:259) ~[httpcore-4.4.5.jar!/:4.4.5]
        at org.apache.http.impl.DefaultBHttpClientConnection.receiveResponseHeader(DefaultBHttpClientConnection.java:163) ~[httpcore-4.4.5.jar!/:4.4.5]
        at org.apache.http.impl.conn.CPoolProxy.receiveResponseHeader(CPoolProxy.java:167) ~[httpclient-4.5.2.jar!/:4.5.2]
        at org.apache.http.protocol.HttpRequestExecutor.doReceiveResponse(HttpRequestExecutor.java:273) ~[httpcore-4.4.5.jar!/:4.4.5]
        at org.apache.http.protocol.HttpRequestExecutor.execute(HttpRequestExecutor.java:125) ~[httpcore-4.4.5.jar!/:4.4.5]
        at org.apache.http.impl.execchain.MainClientExec.createTunnelToTarget(MainClientExec.java:472) ~[httpclient-4.5.2.jar!/:4.5.2]
        at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:397) ~[httpclient-4.5.2.jar!/:4.5.2]
        at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:236) ~[httpclient-4.5.2.jar!/:4.5.2]
        at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:184) ~[httpclient-4.5.2.jar!/:4.5.2]
        at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:88) ~[httpclient-4.5.2.jar!/:4.5.2]
        at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110) ~[httpclient-4.5.2.jar!/:4.5.2]
        at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:184) ~[httpclient-4.5.2.jar!/:4.5.2]
        ... 21 common frames omitted

**Comment by bytefish** [comment]
I will take a look at it. 😎

**Comment by bytefish** [comment]
Are you using SSL Certificates? Is the Username Password correct?

**Comment by bytefish** [comment]
The main problem seems to be this line: 

```
Caused by: org.apache.http.ProtocolException: The server failed to respond with a valid HTTP response
at org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:151) 
```

I will try to find out, why this happens with Proxies and how it can be debugged a little better, than right now.

**Comment by BaymaxGithub** [comment]
SSL Certificates? No,I follow  this  blog--"Send messages from Spring Boot to Ionic 2 over FCM"to use your librariy.It's seem not use SSL Certificates.

**Comment by bytefish** [comment]
Here is what I would do to trace the problem: First of all I would try to increase the Apache HttpClient Logging to the most verbose Level. You can see how to configure the Logging here: https://hc.apache.org/httpcomponents-client-4.5.x/logging.html. If that doesn't work, I would turn on Wireshark (https://www.wireshark.org) and trace what is really being sent and received from the server.

I am quite sure, there is a Firewall blocking you. But it is hard to say with only the Stacktrace. 

Turn on Logging first. And if this doesn't work, then try to use Wireshark to see what is sent and received.

**Comment by bytefish** [comment]
If you have never used Wireshark, then this is a nice tutorial: https://www.lifewire.com/wireshark-tutorial-4143298.

**Comment by BaymaxGithub** [comment]
It's very kind of you,I'll try as you say.And What do you mean by "SSL Certificates",I need use SSL Certificates?

**Comment by bytefish** [comment]
I know, that tracing such problems is hard. But with Logging and Wireshark you will find out,.

Nono, you don't need to use SSL Certificates. It was just a guess, where the problen could be.

**Comment by BaymaxGithub** [comment]
ok,I'll do as you say at once.Thank you again.
