### ISSUE TITLE
fcmClient.send(DataMulticastMessage) throwing NoSuchMethodError.

### ISSUE THREAD

**Issue by scottcarter87** [bytefish/FcmJava#35]
I am trying to use version 2.4 of FcmJava to post a DataMultiCastMessage and the following error is being thrown.

java.lang.NoSuchMethodError: org.apache.http.client.methods.RequestBuilder.post(Ljava/lang/String;)Lorg/apache/http/client/methods/RequestBuilder;

	at de.bytefish.fcmjava.client.http.apache.DefaultHttpClient.buildPostRequest(DefaultHttpClient.java:128)
	at de.bytefish.fcmjava.client.http.apache.DefaultHttpClient.internalPost(DefaultHttpClient.java:98)
	at de.bytefish.fcmjava.client.http.apache.DefaultHttpClient.post(DefaultHttpClient.java:195)
	at de.bytefish.fcmjava.client.FcmClient.post(FcmClient.java:97)
	at de.bytefish.fcmjava.client.FcmClient.send(FcmClient.java:53)

**Comment by scottcarter87** [comment]
Update.  After debugging for a bit the issue seems to be my apache httpcomponents version (4.3) the constructor for RequestBuilder.post in version 4.3 does not take arguments and the version first introduced a method to do that is 4.4.  I upgraded to 4.4.1 and now I am getting ssl verification errors but I am further along.

de.bytefish.fcmjava.http.exceptions.HttpCommunicationException: Error making POST Request

	at de.bytefish.fcmjava.client.http.apache.DefaultHttpClient.post(DefaultHttpClient.java:197)
	at de.bytefish.fcmjava.client.FcmClient.post(FcmClient.java:97)
	at de.bytefish.fcmjava.client.FcmClient.send(FcmClient.java:53)
	at com.powerupcharger.app.integration.charger.FirebaseTest.test(FirebaseTest.java:29)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.MethodInvocationHelper$1.runTestMethod(MethodInvocationHelper.java:200)
	at org.springframework.test.context.testng.AbstractTestNGSpringContextTests.run(AbstractTestNGSpringContextTests.java:171)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.testng.internal.MethodInvocationHelper.invokeHookable(MethodInvocationHelper.java:212)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:707)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:348)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:343)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:305)
	at org.testng.SuiteRunner.run(SuiteRunner.java:254)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:72)
	at org.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:127)
Caused by: javax.net.ssl.SSLPeerUnverifiedException: Host name 'fcm.googleapis.com' does not match the certificate subject provided by the peer (CN=*.googleapis.com, O=Google Inc, L=Mountain View, ST=California, C=US)
	at org.apache.http.conn.ssl.SSLConnectionSocketFactory.verifyHostname(SSLConnectionSocketFactory.java:465)
	at org.apache.http.conn.ssl.SSLConnectionSocketFactory.createLayeredSocket(SSLConnectionSocketFactory.java:395)
	at org.apache.http.conn.ssl.SSLConnectionSocketFactory.connectSocket(SSLConnectionSocketFactory.java:353)
	at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:134)
	at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:353)
	at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:380)
	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:236)
	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:184)
	at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:88)
	at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110)
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:184)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:82)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:107)
	at de.bytefish.fcmjava.client.http.apache.DefaultHttpClient.internalPost(DefaultHttpClient.java:98)
	at de.bytefish.fcmjava.client.http.apache.DefaultHttpClient.post(DefaultHttpClient.java:195)

**Comment by scottcarter87** [comment]
Final update.  I upgrade httpclient again to 4.5.3 and everything seems to be working fine now.  Might be worthwhile to include the minimum httpclient version required for this library in the README since it took me a bit of digging to get to the bottom of this.

**Comment by bytefish** [comment]
Thank you very much for your detailed analysis and great it works. 😎 Yes, I will add a note to the README on the top, which is stating the minimum Apache HttpClient Version, when I get home next week. 👍

**Comment by bytefish** [comment]
@scottcarter87 In the Maven POM I have defined the Apache HttpComponents Version ``4.5.2``. Apparently Maven picked a Version Number lower than it. 🤔 Do you happen to know how I have to define the Maven POM, so that this doesn't happen? My Maven skills are limited. 😳

**Comment by scottcarter87** [comment]
@bytefish Sorry for the slow response.  You will want to update your dependency management section in the top level pom with the version of Apache HttpClient and then define that as a dependency in your sub modules without a version so it inherits from the parent pom.  That should be all you need to do.  Not sure if this would break some people projects though since this could effectively cause 2 versions of Apache HttpClient to be installed if somebody had a project like mine where spring boot starter pulls in Apache HttpClient for me and needed to be overridden.  The other option would be to change your code to use the noarg constructor for RequestBuilder.post which will cover a wider range of versions of Apache HttpClient.  Not sure if there would be other issues with doing that though.  Hope this helps.

**Comment by bytefish** [comment]
@scottcarter87 I don't know. Shouldn't this be done on the user side? 

Like it is done here:

* https://github.com/ralscha/blog/blob/master/push/server/pom.xml#L59
