### ISSUE TITLE
Insufficient handling with api response: de.bytefish.fcmjava.model.enums.ErrorCodeEnum

### ISSUE THREAD

**Issue by sayseakleng** [bytefish/FcmJava#7]
java.lang.RuntimeException: java.lang.RuntimeException: com.fasterxml.jackson.databind.exc.InvalidFormatException: Can not construct instance of de.bytefish.fcmjava.model.enums.ErrorCodeEnum from String value 'InvalidParameters': value not one of declared Enum instance names: [InvalidRegistration, MessageTooBig, DeviceMessageRateExceeded, InvalidTtl, TopicsMessageRateExceeded, InternalServerError, InvalidPackageName, MismatchSenderId, MissingRegistration, Unavailable, NotRegistered, InvalidDataKey]
 at [Source: {"multicast_id":4995113026256981074,"success":0,"failure":1,"canonical_ids":0,"results":[{"error":"InvalidParameters"}]}; line: 1, column: 91] (through reference chain: de.bytefish.fcmjava.responses.FcmMessageResponse["results"]->java.util.ArrayList[0]->de.bytefish.fcmjava.responses.FcmMessageResultItem["error"])
	at de.bytefish.fcmjava.client.http.HttpClient.post(HttpClient.java:51)
	at de.bytefish.fcmjava.client.FcmClient.post(FcmClient.java:99)
	at de.bytefish.fcmjava.client.FcmClient.send(FcmClient.java:70)
	at com.kdemo.gcm.TestFCM.test(TestFCM.java:43)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:86)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:678)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192)

**Comment by bytefish** [comment]
I have added the missing enum value. I will make a Bugfix release in the next days.

**Comment by bytefish** [comment]
I have fixed the bug in Release 0.8, which will be available in some hours. Please reopen the ticket, if it doesn't fix the problem.
